autofit:
- get_dist # Cant get it to install, even in optional requirements.
- mcmc # Zeus section in merged mcmc.py fails Test Model Initialization.
- zeus_plotter # Test Model Iniitalization no good.
- dynesty_plotter # Test Model Iniitalization no good.
- emcee_plotter # Needs result.search_internal, None under PYAUTO_TEST_MODE=2.
- nautilus_plotter # Needs result.search_internal, None under PYAUTO_TEST_MODE=2.
- start_point # bug https://github.com/PyAutoLabs/PyAutoFit/issues/1017
autogalaxy:
- tutorial_searches
- gui/light_centre # GUI scripts cannot be run
- gui/mask_extra_galaxies # GUI scripts cannot be run
- gui/mask # GUI scripts cannot be run
- gui/extra_galaxies_centres # GUI scripts cannot be run
- examples/searches # Test mode breaks search visualization.
- data_fitting # Test mode breaks .fits file output
autolens:
- tutorial_searches
- tutorial_5_borders # Cant get right masks, need proper update.
- tutorial_6_model_fit # InversionException due to test mode
- gui/extra_galaxies_centres # GUI scripts cannot be run
- gui/mask_extra_galaxies # GUI scripts cannot be run
- gui/lens_light_centre # GUI scripts cannot be run
- gui/mask # GUI scripts cannot be run
- gui/positions # GUI scripts cannot be run
- deflections # Output HDU not supported for VectorYX Detections.
- deflections_source_snr # Output HDU not supported for VectorYX Detections.
- time_delays # Test mode does not support cosmology ift
- hpc/example_cpu # HPC paths dont exist locally.
- examples/searches # Test mode breaks search visualization.
- data_fitting # Test mode breaks .fits file output
- mass_stellar_dark/modeling # Requires CSE to be JAX enabled.
- mass_stellar_dark/slam # Requires CSE to be JAX enabled.
- shapelets/modeling # Issue with JAX, claude remind me about this when you next look at build.
- detect/database # Unsure but not a feature actively used currently.
- sensitivity/slam_source_parametric # Need to update when visuaization refactored.
- sensitivity/slam_source_pixelized # Need to update, when visuaization refactored.
- plot/visuals # Bugged, but visuals being refactored soon.
autofit_test:
- Drawer # Only works with sensitivity mapper to not raise InitializerException.
- session/general # Session mostly works but not maintaining currently.
- session/multi_analysis # Session mostly works but not maintaining currently.
autolens_test: []
howtogalaxy: []
howtolens:
- tutorial_searches
- tutorial_5_borders # Cant get right masks, need proper update.
- tutorial_6_model_fit # InversionException due to test mode
howtofit: []