#!/usr/bin/env python
"""
Create a GitHub Issue with the release readiness report and assign Copilot for analysis.

Usage:
    python create_analysis_issue.py report.json --run-id <id> [--repo <owner/repo>] [--dry-run]
"""

import json
import subprocess
import sys
from argparse import ArgumentParser
from datetime import date
from pathlib import Path


MAX_BODY_LENGTH = 60000  # GitHub limit is 65535, leave margin


def build_issue_body(report: dict, run_id: str, repo: str) -> str:
    """Construct the GitHub Issue body from the consolidated report."""
    lines = []

    ready = report.get("ready", False)
    status = "READY" if ready else "NOT READY"
    summary = report.get("summary", {})

    lines.append("## Context")
    lines.append("")
    lines.append("This issue was auto-generated by the PyAuto release pipeline.")
    if run_id and repo:
        lines.append(f"**Workflow run:** https://github.com/{repo}/actions/runs/{run_id}")
    lines.append(f"**Status:** {status}")
    lines.append("")

    lines.append("## Task for Copilot")
    lines.append("")
    lines.append("Analyze the test results below and provide:")
    lines.append("1. Root cause analysis for each failure")
    lines.append("2. Classification: source code bug, workspace issue, environment issue, or flaky test")
    lines.append("3. Suggested fixes with specific file paths and code changes")
    lines.append("4. Overall go/no-go recommendation for release")
    lines.append("5. Priority ordering of failures to fix")
    lines.append("")

    # Summary table
    lines.append("## Test Results Summary")
    lines.append("")
    lines.append(f"| Passed | Failed | Skipped | Timeout |")
    lines.append(f"|--------|--------|---------|---------|")
    lines.append(f"| {summary.get('passed', 0)} | {summary.get('failed', 0)} | {summary.get('skipped', 0)} | {summary.get('timeout', 0)} |")
    lines.append("")

    # Per-project breakdown
    per_project = report.get("per_project", {})
    if per_project:
        lines.append("## Per-Project Breakdown")
        lines.append("")
        lines.append("| Project | Passed | Failed | Skipped | Timeout |")
        lines.append("|---------|--------|--------|---------|---------|")
        for proj, counts in sorted(per_project.items()):
            lines.append(f"| {proj} | {counts.get('passed', 0)} | {counts.get('failed', 0)} | {counts.get('skipped', 0)} | {counts.get('timeout', 0)} |")
        lines.append("")

    # Detailed failures
    failures = report.get("failures", [])
    if failures:
        lines.append("## Detailed Failures")
        lines.append("")
        for i, f in enumerate(failures):
            lines.append(f"### Failure {i+1}: `{f.get('file', 'unknown')}`")
            lines.append("")
            lines.append(f"- **Classification:** {f.get('classification', 'unknown')}")
            lines.append(f"- **Error:** {f.get('error_message', 'N/A')[:500]}")
            lines.append(f"- **Duration:** {f.get('duration_seconds', 0):.1f}s")

            # PR correlation
            correlations = report.get("failure_pr_correlations", {})
            file_path = f.get("file", "")
            if file_path in correlations:
                for corr in correlations[file_path]:
                    lines.append(f"- **Recently modified** in [{corr['pr_title']}]({corr['pr_url']})")

            tb = f.get("traceback", "")
            if tb:
                tb_lines = tb.strip().splitlines()[-30:]
                lines.append("")
                lines.append("<details><summary>Traceback (last 30 lines)</summary>")
                lines.append("")
                lines.append("```")
                lines.extend(tb_lines)
                lines.append("```")
                lines.append("</details>")
            lines.append("")

    # Skipped tests
    skipped = report.get("skipped", [])
    if skipped:
        lines.append("## Skipped Tests")
        lines.append("")
        lines.append("| Script | Reason |")
        lines.append("|--------|--------|")
        for s in skipped[:50]:  # Limit to 50 to stay within body size
            lines.append(f"| `{Path(s.get('file', '')).name}` | {s.get('skip_reason', 'N/A')} |")
        if len(skipped) > 50:
            lines.append(f"| ... | {len(skipped) - 50} more skipped |")
        lines.append("")

    # Changes since last release
    pr_changes = report.get("pr_changes", [])
    if pr_changes:
        lines.append("## Changes Since Last Release")
        lines.append("")
        for pc in pr_changes[:20]:
            lines.append(f"- [{pc['title']}]({pc['url']}) ({pc['repo']})")
        lines.append("")

    body = "\n".join(lines)

    # Truncate if too long
    if len(body) > MAX_BODY_LENGTH:
        body = body[:MAX_BODY_LENGTH] + "\n\n*... truncated (full report in workflow artifacts)*"

    return body


def main():
    parser = ArgumentParser(description="Create release readiness GitHub issue")
    parser.add_argument("report", type=Path, help="Path to consolidated JSON report")
    parser.add_argument("--run-id", type=str, default="", help="GitHub Actions run ID")
    parser.add_argument("--repo", type=str, default="PyAutoLabs/PyAutoHands",
                        help="GitHub repository (owner/repo)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print issue body without creating")

    args = parser.parse_args()

    with open(args.report) as f:
        report = json.load(f)

    today = date.today().isoformat()
    title = f"Release Readiness Report — {today}"
    body = build_issue_body(report, args.run_id, args.repo)

    if args.dry_run:
        print(f"Title: {title}")
        print(f"Body length: {len(body)} chars")
        print("---")
        print(body)
        return

    # Create the issue
    try:
        result = subprocess.run(
            ["gh", "issue", "create",
             "--repo", args.repo,
             "--title", title,
             "--body", body,
             "--label", "release,ai-analysis",
             "--assignee", "copilot"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            issue_url = result.stdout.strip()
            print(f"Issue created: {issue_url}")
        else:
            # Copilot assignment may fail — retry without assignee
            print(f"Failed with copilot assignee: {result.stderr}", file=sys.stderr)
            print("Retrying without copilot assignment...", file=sys.stderr)
            result = subprocess.run(
                ["gh", "issue", "create",
                 "--repo", args.repo,
                 "--title", title,
                 "--body", body,
                 "--label", "release,ai-analysis"],
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode == 0:
                issue_url = result.stdout.strip()
                print(f"Issue created (without copilot): {issue_url}")
            else:
                print(f"Failed to create issue: {result.stderr}", file=sys.stderr)
                sys.exit(1)
    except FileNotFoundError:
        print("gh CLI not found — skipping issue creation", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
