#!/usr/bin/env python
"""
Run workspace scripts across one or more workspaces and produce summary reports.

Usage:
    python run_all.py                          # all 10 workspaces
    python run_all.py autolens                 # just autolens_workspace
    python run_all.py autolens_test autofit    # specific workspaces
    python run_all.py howtolens                # just HowToLens
    python run_all.py euclid                   # just the Euclid pipeline

Reports default to a Mind-style run-log hierarchy under
<autohands>/../run_logs/runs/<run-type>/<YYYY>/<MM>/<UTC-timestamp>/ (months are
zero-padded so lexical order is chronological). A sibling `run_logs/latest`
symlink points at the most recent successful run, so every release-prep run is
preserved. The run-type segment comes from --run-type (default "smoke"); a
release-prep mega-run passes --run-type release. Each run also refreshes
run_logs/index.md (one row per run, newest first) and run_logs/AGENTS.md (a
static description of the layout). Pass --results-dir to override the target
(CI uses this); in that mode the symlink, index and AGENTS.md are not touched.

Per-script timeout defaults to 300s and can be overridden via --timeout-secs.
This is forwarded to subprocesses via BUILD_SCRIPT_TIMEOUT.

Each workspace also gets a test_report.md in its root for easy access.
"""

import datetime
import os
import shutil
import subprocess
import sys
from argparse import ArgumentParser
from pathlib import Path

AUTOHANDS_DIR = Path(__file__).parent
PYAUTOBASE = AUTOHANDS_DIR.parent.parent  # PyAutoLabs/
RESULTS_BASE = AUTOHANDS_DIR.parent / "run_logs"
DEFAULT_RUN_TYPE = "smoke"

def _load_workspaces() -> dict:
    """The run matrix, from autohands/config/workspaces.yaml (Build policy).
    Strict: the file is in-repo and load-bearing — fail loudly if absent."""
    import yaml

    cfg = yaml.safe_load((AUTOHANDS_DIR / "config" / "workspaces.yaml").read_text())
    return {
        key: (spec["repo"], spec["report"])
        for key, spec in cfg["run_all"].items()
    }


WORKSPACES = _load_workspaces()

DEFAULT_TIMEOUT_SECS = 300


def utc_run_timestamp() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")


def update_latest_symlink(run_dir: Path, base: Path | None = None) -> None:
    """Atomically point <base>/latest at run_dir (absolute-resolved)."""
    base = base or RESULTS_BASE
    latest = base / "latest"
    tmp = base / ".latest.tmp"
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
    tmp.symlink_to(run_dir.resolve(), target_is_directory=True)
    os.replace(tmp, latest)


def run_dir_for(timestamp: str, run_type: str, base: Path | None = None) -> Path:
    """Nested run directory: <base>/runs/<run-type>/<YYYY>/<MM>/<timestamp>/.

    Months are zero-padded (derived from the ``YYYY-MM-...`` timestamp) so the
    directory tree sorts lexically = chronologically, mirroring PyAutoMind's
    ``complete/<YYYY>/<MM>/`` layout.
    """
    base = base or RESULTS_BASE
    year, month = timestamp[:4], timestamp[5:7]
    return (base / "runs" / run_type / year / month / timestamp).resolve()


# Static description of the run-log layout, refreshed on every run so it never
# drifts from the writer. Readers listed here are the 2026-07 lockstep set.
AGENTS_MD = """\
# PyAutoHands run logs (`run_logs/`)

Persistent, on-disk history of every `autohands run_all` mega-run. This tree is
**gitignored** — it is local run state, not source. It replaced the old
`test_results/` folder (renamed 2026-07 so the name no longer reads as unit
tests) in the Phase-3 run-log relayout.

## Layout

```
run_logs/
  runs/<run-type>/<YYYY>/<MM>/<UTC-timestamp>/   # one directory per run
      report.json        # aggregated verdict (ready, summary, per_project, ...)
      report.md          # human-readable report
      <project>__<dir>__script.json / .md        # per-shard results
  latest -> runs/.../<newest-run>/               # absolute symlink, newest OK run
  index.md               # one row per run, newest first (regenerated each run)
  AGENTS.md              # this file
```

- `<run-type>` is the mega-run mode (`smoke` by default; `release` for a
  release-prep run — `run_all.py --run-type`). Months are zero-padded so
  lexical order is chronological.

## Who reads what

- `run_logs/latest/report.json` — PyAutoHeart `heart/checks/test_run.py`
  (readiness verdict count enrichment) and `scripts/health_release.sh`
  (`health release` dashboard).
- `run_logs/latest/` per-shard JSON — PyAutoHeart `heart/checks/script_timing.py`
  (rolling per-script duration baselines; `heart/tick.sh` guards on
  `run_logs/latest`).
- `run_logs/index.md` — quick human lookup of run history.

Do not hand-edit run directories; they are regenerated by `run_all.py`.
"""


def write_agents_md(base: Path | None = None) -> None:
    """Write the static AGENTS.md describing the run-log layout."""
    base = base or RESULTS_BASE
    base.mkdir(parents=True, exist_ok=True)
    (base / "AGENTS.md").write_text(AGENTS_MD)


def _read_run_summary(run_dir: Path) -> dict | None:
    """Best-effort summary for one run dir from its report.json.

    Returns {date, run_type, passed, failed, skipped, timeout, per_project,
    rel_link} or None if the run has no readable report.json.
    """
    import json

    report_path = run_dir / "report.json"
    try:
        report = json.loads(report_path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    summary = report.get("summary", {}) or {}
    per_project = report.get("per_project", {}) or {}
    # runs/<run-type>/<YYYY>/<MM>/<timestamp> — run-type is 3 levels up.
    ts = run_dir.name
    try:
        run_type = run_dir.parent.parent.parent.name
    except Exception:
        run_type = "?"
    return {
        "timestamp": ts,
        "date": ts[:10],
        "run_type": run_type,
        "passed": summary.get("passed", 0),
        "failed": summary.get("failed", 0),
        "skipped": summary.get("skipped", 0),
        "timeout": summary.get("timeout", 0),
        "per_project": per_project,
        "rel_link": "/".join(run_dir.resolve().relative_to(base_of(run_dir)).parts),
    }


def base_of(run_dir: Path) -> Path:
    """The run_logs base that contains run_dir (…/run_logs/runs/<type>/…)."""
    # run_dir = <base>/runs/<run-type>/<YYYY>/<MM>/<timestamp>
    return run_dir.resolve().parents[4]


def _fmt_per_project(per_project: dict) -> str:
    """Compact per-project pass/fail string: ``autolens 242/5, ...``."""
    parts = []
    for proj in sorted(per_project):
        c = per_project[proj]
        parts.append(f"{proj} {c.get('passed', 0)}/{c.get('failed', 0)}")
    return "; ".join(parts)


def regenerate_index(base: Path | None = None) -> Path:
    """Rebuild <base>/index.md from every run on disk (newest first).

    Regenerate-from-disk is deliberately idempotent and robust: it never trusts
    a previously-written index, so a crashed or hand-moved run self-heals on the
    next run.
    """
    base = base or RESULTS_BASE
    runs_root = base / "runs"
    rows = []
    if runs_root.is_dir():
        # runs/<run-type>/<YYYY>/<MM>/<timestamp>/
        for run_dir in runs_root.glob("*/*/*/*"):
            if not run_dir.is_dir():
                continue
            row = _read_run_summary(run_dir)
            if row is not None:
                rows.append(row)
    rows.sort(key=lambda r: r["timestamp"], reverse=True)

    lines = [
        "# PyAutoHands run-log index",
        "",
        "One row per `autohands run_all` mega-run, newest first. Regenerated on "
        "every run from the run directories on disk. See `AGENTS.md` for the "
        "layout.",
        "",
        "| Date | Type | Passed | Failed | Skipped | Per-project (pass/fail) | Run |",
        "|------|------|--------|--------|---------|-------------------------|-----|",
    ]
    for r in rows:
        report_link = f"{r['rel_link']}/report.md"
        lines.append(
            f"| {r['date']} | {r['run_type']} | {r['passed']} | {r['failed']} "
            f"| {r['skipped']} | {_fmt_per_project(r['per_project'])} "
            f"| [{r['timestamp']}]({report_link}) |"
        )
    lines.append("")

    index_path = base / "index.md"
    base.mkdir(parents=True, exist_ok=True)
    index_path.write_text("\n".join(lines))
    return index_path

# Local venv path — used when it exists, otherwise fall back to system python
LOCAL_VENV_PYTHON = Path.home() / "venv" / "PyAuto" / "bin" / "python3"


def _resolve_python() -> str:
    """Pick the Python interpreter: local venv if available, else system."""
    if LOCAL_VENV_PYTHON.exists():
        return str(LOCAL_VENV_PYTHON)
    return sys.executable


def run_workspace(name, workspace_dir, project, results_dir, python, timeout_secs):
    """Run all script directories for a single workspace."""
    scripts_dir = workspace_dir / "scripts"
    if not scripts_dir.exists():
        print(f"  Skipping {name}: no scripts/ directory")
        return

    directories = sorted(
        p.name for p in scripts_dir.iterdir()
        if p.is_dir() and p.name != "__pycache__"
    )
    # Flat scripts/ (e.g. euclid_strong_lens_modeling_pipeline) → run the
    # directory itself as a single unit rather than iterating subdirs.
    iter_dirs = directories or [""]

    # Ensure child processes (run_python.py -> build_util.py) use the same
    # interpreter and timeout for running scripts.
    env = os.environ.copy()
    env["BUILD_PYTHON_INTERPRETER"] = python
    env["BUILD_SCRIPT_TIMEOUT"] = str(timeout_secs)
    env["PYTHONUNBUFFERED"] = "1"

    for directory in iter_dirs:
        rel_dir = "scripts" if directory == "" else f"scripts/{directory}"
        print(f"\n  Running {name} / {rel_dir} ...")
        cmd = [
            python,
            str(AUTOHANDS_DIR / "run_python.py"),
            project,
            rel_dir,
            "--report-dir", str(results_dir),
        ]
        subprocess.run(cmd, cwd=str(workspace_dir), env=env)


def main():
    parser = ArgumentParser(description="Run all workspace scripts and aggregate results")
    parser.add_argument(
        "workspaces",
        nargs="*",
        default=None,
        choices=list(WORKSPACES.keys()),
        help="Workspaces to run (default: all)",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=None,
        help=(
            "Directory for result files (default: "
            "PyAutoHands/run_logs/runs/<run-type>/<YYYY>/<MM>/<UTC-timestamp>/, "
            "with a run_logs/latest symlink updated on success)."
        ),
    )
    parser.add_argument(
        "--run-type",
        type=str,
        default=DEFAULT_RUN_TYPE,
        help=(
            f"Mega-run mode, used as the <run-type> path segment (default: "
            f"'{DEFAULT_RUN_TYPE}'). A release-prep run passes --run-type release."
        ),
    )
    parser.add_argument(
        "--timeout-secs",
        type=int,
        default=DEFAULT_TIMEOUT_SECS,
        help=(
            f"Per-script timeout in seconds (default: {DEFAULT_TIMEOUT_SECS}). "
            "Forwarded to subprocesses via BUILD_SCRIPT_TIMEOUT env var."
        ),
    )
    args = parser.parse_args()

    workspaces = args.workspaces or list(WORKSPACES.keys())
    python = _resolve_python()
    timeout_secs = args.timeout_secs

    user_supplied_results_dir = args.results_dir is not None
    if user_supplied_results_dir:
        results_dir = args.results_dir.resolve()
        if results_dir.exists():
            shutil.rmtree(results_dir)
        results_dir.mkdir(parents=True)
    else:
        results_dir = run_dir_for(utc_run_timestamp(), args.run_type)
        results_dir.mkdir(parents=True)

    print(f"Python: {python}")
    print(f"Results directory: {results_dir}")
    print(f"Per-script timeout: {timeout_secs}s")
    print(f"Workspaces: {', '.join(workspaces)}")

    from slow_skip_check import (
        find_slow_skips,
        find_needs_fix_skips,
        format_warning_banner,
        format_report_section,
    )
    ws_dirs_for_scan = [
        PYAUTOBASE / WORKSPACES[k][0]
        for k in workspaces
        if (PYAUTOBASE / WORKSPACES[k][0]).exists()
    ]
    slow_skips = find_slow_skips(ws_dirs_for_scan)
    needs_fix_skips = find_needs_fix_skips(ws_dirs_for_scan)
    if slow_skips:
        print(format_warning_banner(slow_skips, category="slow", timeout_secs=timeout_secs))
    if needs_fix_skips:
        print(format_warning_banner(needs_fix_skips, category="needs_fix"))

    for ws_key in workspaces:
        ws_name, project = WORKSPACES[ws_key]
        ws_dir = PYAUTOBASE / ws_name
        if not ws_dir.exists():
            print(f"\nSkipping {ws_key}: {ws_dir} not found")
            continue

        print(f"\n{'=' * 60}")
        print(f"  {ws_name}")
        print(f"{'=' * 60}")
        run_workspace(ws_key, ws_dir, project, results_dir, python, timeout_secs)

        # Copy per-workspace markdown summaries into the workspace root
        for md_file in results_dir.glob(f"{project}__*.md"):
            dest = ws_dir / "test_report.md"
            shutil.copy2(md_file, dest)
            print(f"  Summary written to {dest}")

    # Aggregate all results
    print(f"\n{'=' * 60}")
    print("  Aggregating results")
    print(f"{'=' * 60}")

    from aggregate_results import aggregate, generate_markdown

    report = aggregate(results_dir)
    report["slow_skips"] = [s.to_dict() for s in slow_skips]
    report["needs_fix_skips"] = [s.to_dict() for s in needs_fix_skips]

    import json
    with open(results_dir / "report.json", "w") as f:
        json.dump(report, f, indent=2)

    md = generate_markdown(report)
    md_path = results_dir / "report.md"
    with open(md_path, "w") as f:
        f.write(md)

    # Print summary to stdout
    s = report.get("summary", {})
    total = sum(s.values())
    print(f"\n{total} scripts total: "
          + ", ".join(f"{v} {k}" for k, v in sorted(s.items())))

    per_project = report.get("per_project", {})
    if per_project:
        print(f"\n{'Project':<30} {'Passed':>7} {'Failed':>7} {'Skipped':>8} {'Timeout':>8}")
        print("-" * 62)
        for proj, counts in sorted(per_project.items()):
            print(f"{proj:<30} {counts.get('passed', 0):>7} {counts.get('failed', 0):>7} "
                  f"{counts.get('skipped', 0):>8} {counts.get('timeout', 0):>8}")

    failures = report.get("failures", [])
    if failures:
        print(f"\n{len(failures)} failure(s) — see {md_path}")
    else:
        print(f"\nAll tests passed! Full report: {md_path}")

    if slow_skips:
        print(format_warning_banner(slow_skips, category="slow", timeout_secs=timeout_secs))
    if needs_fix_skips:
        print(format_warning_banner(needs_fix_skips, category="needs_fix"))

    if not user_supplied_results_dir:
        try:
            update_latest_symlink(results_dir)
            print(f"\nlatest symlink → {results_dir}")
        except OSError as exc:
            print(f"\nCould not update latest symlink: {exc}", file=sys.stderr)
        # Refresh the run-log index (regenerate-from-disk) and the static
        # layout doc so history stays browsable and self-documenting.
        try:
            index_path = regenerate_index()
            write_agents_md()
            print(f"index refreshed → {index_path}")
        except OSError as exc:
            print(f"\nCould not refresh run-log index: {exc}", file=sys.stderr)

    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
